### ISSUE TITLE
ssl Internal Error

### ISSUE THREAD

**Issue by bricoletc** [enasequence/enaBrowserTools#57]
Hello, 

First of all thanks for this very useful tool.

I'm getting the following error when running `enaDataGet`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/usr/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/usr/lib/python3.8/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL] internal error (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/enaGroupGet.py", line 190, in <module>
    download_group(accession, group, output_format, dest_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "/usr/bin/enaGroupGet.py", line 140, in download_group
    download_data_group(group, accession, output_format, group_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "/usr/bin/enaGroupGet.py", line 88, in download_data_group
    download_report(group, utils.get_group_result(group), accession, temp_file_path, subtree)
  File "/usr/bin/enaGroupGet.py", line 68, in download_report
    response = utils.get_report_from_portal(search_url)
  File "/usr/bin/utils.py", line 476, in get_report_from_portal
    response = urlrequest.urlopen(request, context=gcontext)
  File "/usr/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.8/urllib/request.py", line 1393, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL] internal error (_ssl.c:1123)>
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details.
```

I've done a little bit of reading and found the `ssl` module error is raised by the underlying OpenSsl library (https://docs.python.org/3/library/ssl.html#ssl.SSLError). 

Confirming this is an Openssl issue, the machine (ubuntu focal) where the error occurs has this version:
```
$ apt show openssl
Package: openssl
Version: 1.1.1f-1ubuntu2.1
Priority: important
Section: utils
Origin: Ubuntu
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Debian OpenSSL Team <pkg-openssl-devel@lists.alioth.debian.org>
Bugs: https://bugs.launchpad.net/ubuntu/+filebug
Installed-Size: 1287 kB
Depends: libc6 (>= 2.15), libssl1.1 (>= 1.1.1)
Suggests: ca-certificates
Homepage: https://www.openssl.org/
Task: minimal
Download-Size: 620 kB
APT-Manual-Installed: no
APT-Sources: http://archive.ubuntu.com/ubuntu focal-updates/main amd64 Packages
Description: Secure Sockets Layer toolkit - cryptographic utility
```

Whereas on a Fedora machine `enaDataGet` runs fine, where OpenSsl is following version:
```
Name        : openssl
Arch        : x86_64
Epoch       : 1
Version     : 1.0.2k
Release     : 8.el7
Size        : 814 k
Repo        : installed
From repo   : anaconda
Summary     : Utilities from the general purpose cryptography library with TLS implementation
URL         : http://www.openssl.org/
Licence     : OpenSSL
Description : The OpenSSL toolkit provides support for secure communications between
            : machines. OpenSSL includes a certificate management tool and shared
            : libraries which provide various cryptographic algorithms and
            : protocols.
```

Any idea what is up here?

**Comment by oligoelemento** [comment]
I solved the issue removing the SLLContext from the urlopen request from the line 470 in utils.py:
return urlrequest.urlopen(request) #, context=gcontext)
