### ISSUE TITLE
HTTPError after enaGroupGet

### ISSUE THREAD

**Issue by lvelosuarez** [enasequence/enaBrowserTools#59]
Hi! 
First of all thanks for writing this software. It's been a couple of weeks that enaGroupGet is throwing me this error no matter my python version (I've tried 2.7,3.6 and 3.7). It's related to the getRead.py script and I don't know how to solve it. 
Thanks for having a look, 
Lourdes

Traceback (most recent call last):
  File "enaGroupGet.py", line 189, in <module>
    download_group(accession, group, output_format, dest_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "enaGroupGet.py", line 138, in download_group
    download_data_group(group, accession, output_format, group_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "enaGroupGet.py", line 95, in download_data_group
    download_data(group, data_accession, output_format, group_dir, fetch_wgs, extract_wgs, expanded, fetch_meta, fetch_index, aspera)
  File "enaGroupGet.py", line 83, in download_data
    readGet.download_files(data_accession, output_format, group_dir, fetch_index, fetch_meta, aspera)
  File "/WORKING_DIRECTORY/lvelo/enaBrowserTools/enaBrowserTools-1.5.5/python/readGet.py", line 90, in download_files
    utils.download_report_from_portal(search_url, temp_file)
  File "/WORKING_DIRECTORY/lvelo/enaBrowserTools/enaBrowserTools-1.5.5/python/utils.py", line 452, in download_report_from_portal
    response = get_report_from_portal(url)
  File "/WORKING_DIRECTORY/lvelo/enaBrowserTools/enaBrowserTools-1.5.5/python/utils.py", line 449, in get_report_from_portal
    return urllib2.urlopen(request)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/home/lvelo/working_directory/my-envs/ena2.7/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
HTTPError: HTTP Error 400: Bad Request
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact datasubs@ebi.ac.uk for assistance. with the above error details.
****

**Comment by lilim-ebi** [comment]
Closing due to inactivity.

**Comment by lilim-ebi** [comment]
Closing due to inactivity.
