### ISSUE TITLE
Error with retrieving fastq files with enaGroupGet

### ISSUE THREAD

**Issue by chazdm** [enasequence/enaBrowserTools#61]
Hello,

I am trying to retrieve the fastq files for Project SRP199470 but end up with error messages as follows

> (ena) [dmelloc@arc PRJNA544731]$ enaGroupGet -f fastq SRP199470
Traceback (most recent call last):
  File "/home/dmelloc/anaconda3/envs/ena/bin/enaGroupGet.py", line 164, in <module>
    if not utils.is_available(accession):
  File "/home/dmelloc/anaconda3/envs/ena/bin/utils.py", line 242, in is_available
    return (not 'entry is not found' in record.text) and (len(record.getchildren()) > 0)
AttributeError: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

Would really appreciate any assistance to resolve this.

Thank you!

**Comment by mikecuoco** [comment]
@chazdm I solved this by downgrading python to 3.8. `getchildren()` was deprecated in python 3.2 and removed in 3.9 ([source](https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren))

**Comment by chazdm** [comment]
Thanks for your help @mikecuoco

I downgraded python to 3.8 but still ran into errors.

> Traceback (most recent call last):
  File "/home/dmelloc/anaconda3/envs/ena/bin/enaDataGet.py", line 89, in <module>
    elif not utils.is_available(accession):
  File "/home/dmelloc/anaconda3/envs/ena/bin/utils.py", line 240, in is_available
    response = urlrequest.urlopen(url)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 563, in error
    result = self._call_chain(*args)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 755, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 640, in http_response
    response = self.parent.error(
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/home/dmelloc/anaconda3/envs/ena/lib/python3.8/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400:
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact datasubs@ebi.ac.uk for assistance, with the above error details.


Would you be able to provide any further insight into how I might be able to resolve this?
Thank you!
