### ISSUE TITLE
enaDataGet error

### ISSUE THREAD

**Issue by Jigyasa3** [enasequence/enaBrowserTools#70]
Hi all!

I am running into batch raw reads download using enaGroupGet-

code-
`while read line;do /flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet --group read --format fastq ${line};done < segmentac`

where `segmentac` contains-
PRJNA541981
PRJNA544545
PRJNA595160
PRJEB43614
PRJNA622244

I am using python 3.5.2 version.
I found [https://github.com/enasequence/enaBrowserTools/issues/57#issuecomment-858727330](url) and [https://github.com/enasequence/enaBrowserTools/issues/61](url).
But the utils.py file doesn't have `470 in utils.py:
return urlrequest.urlopen(request) #, context=gcontext)`. I have tried on both 3.5.2 and 3.7.3 version of python and getting the same error

Error-
Checking availability of https://www.ebi.ac.uk/ena/browser/api/xml/PRJNA541981
Traceback (most recent call last):
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 190, in <module>
    download_group(accession, group, output_format, dest_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 136, in download_group
    utils.create_dir(group_dir)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/utils.py", line 573, in create_dir
    os.makedirs(dir_path)
  File "/apps/free81/python/3.5.2/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: './PRJNA541981'
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details.
Checking availability of https://www.ebi.ac.uk/ena/browser/api/xml/PRJNA544545
Traceback (most recent call last):
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 190, in <module>
    download_group(accession, group, output_format, dest_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 136, in download_group
    utils.create_dir(group_dir)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/utils.py", line 573, in create_dir
    os.makedirs(dir_path)
  File "/apps/free81/python/3.5.2/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: './PRJNA544545'
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details.
Checking availability of https://www.ebi.ac.uk/ena/browser/api/xml/PRJNA595160
Traceback (most recent call last):
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 190, in <module>
    download_group(accession, group, output_format, dest_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 136, in download_group
    utils.create_dir(group_dir)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/utils.py", line 573, in create_dir
    os.makedirs(dir_path)
  File "/apps/free81/python/3.5.2/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: './PRJNA595160'
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details.
Checking availability of https://www.ebi.ac.uk/ena/browser/api/xml/PRJEB43614
Traceback (most recent call last):
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 190, in <module>
    download_group(accession, group, output_format, dest_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 136, in download_group
    utils.create_dir(group_dir)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/utils.py", line 573, in create_dir
    os.makedirs(dir_path)
  File "/apps/free81/python/3.5.2/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: './PRJEB43614'
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details.
Checking availability of https://www.ebi.ac.uk/ena/browser/api/xml/PRJNA622244
Traceback (most recent call last):
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 190, in <module>
    download_group(accession, group, output_format, dest_dir, fetch_wgs, extract_wgs, fetch_meta, fetch_index, aspera, subtree, expanded)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/enaGroupGet.py", line 136, in download_group
    utils.create_dir(group_dir)
  File "/flash/BourguignonU/DB/enaBrowserTools-1.1.0/python3/utils.py", line 573, in create_dir
    os.makedirs(dir_path)
  File "/apps/free81/python/3.5.2/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
OSError: [Errno 30] Read-only file system: './PRJNA622244'
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details.

**Comment by lilim-ebi** [comment]
Hi,

This error is probably happening because you don't have permission to write to this folder. You can set folders to be writable, however it looks like you're using the root folder, so I would advise against modifying the permissions. Alternatively, if you add an extra argument with `-d`, you can add a destination folder that is already writable.

Please update to the latest version of the tool as well, as some changes were made recently.
