### ISSUE TITLE
enaDataGet - HTTP error 400

### ISSUE THREAD

**Issue by Didoule** [enasequence/enaBrowserTools#78]
Hi all - I had a pipeline which was working great to pull fastq sequences from ENA using enaDataGet and then assemble with SPAdes however it is now no longer working. The error seems to be related to a previous post but I couldn't see what the solution had been. This is the error message I get: 

"Traceback (most recent call last):
  File "/apps/system/easybuild/software/enaBrowserTools/1.6-GCCcore-8.2.0-Python-3.7.2/python3/enaDataGet.py", line 116, in <module>
    readGet.download_files(accession, output_format, dest_dir, fetch_index, fetch_meta, aspera)
  File "/apps/system/easybuild/software/enaBrowserTools/1.6-GCCcore-8.2.0-Python-3.7.2/python3/readGet.py", line 93, in download_files
    lines = utils.download_report_from_portal(search_url)
  File "/apps/system/easybuild/software/enaBrowserTools/1.6-GCCcore-8.2.0-Python-3.7.2/python3/utils.py", line 473, in download_report_from_portal
    response = get_report_from_portal(url)
  File "/apps/system/easybuild/software/enaBrowserTools/1.6-GCCcore-8.2.0-Python-3.7.2/python3/utils.py", line 470, in get_report_from_portal
    return urlrequest.urlopen(request, context=gcontext)
  File "/apps/system/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/apps/system/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/urllib/request.py", line 531, in open
    response = meth(req, response)
  File "/apps/system/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/urllib/request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "/apps/system/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/urllib/request.py", line 569, in error
    return self._call_chain(*args)
  File "/apps/system/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/apps/system/easybuild/software/Python/3.7.2-GCCcore-8.2.0/lib/python3.7/urllib/request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 400: 
ERROR: Something unexpected went wrong please try again.
If problem persists, please contact ENA (https://www.ebi.ac.uk/ena/browser/support) for assistance, with the above error details."

Please can someone let me know how this can be fixed? Many thanks!

**Comment by lilim-ebi** [comment]
Hi,

I think you have an older version of the tool. We made changes in one of our APIs and we updated the enaBrowserTools to work with it. Please update, and if the issue persists, I'll look into it further.
