### ISSUE TITLE
configparser error?

### ISSUE THREAD

**Issue by jjkoehorst** [enasequence/enaBrowserTools#82]
```
python3 enaDataGet.py               
Traceback (most recent call last):
  File "/Volumes/Git/other/enaBrowserTools/python3/enaDataGet.py", line 23, in <module>
    import sequenceGet
  File "/Volumes/Git/other/enaBrowserTools/python3/sequenceGet.py", line 22, in <module>
    import utils
  File "/Volumes/Git/other/enaBrowserTools/python3/utils.py", line 32, in <module>
    from configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/usr/local/Cellar/python@3.12/3.12.2_1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

**Comment by lilim-ebi** [comment]
Hi,

I've been using python3.10 and it worked fine. I get the same issue on 3.12, I'll look into a solution.

**Comment by corneliusroemer** [comment]
Also getting this error on Python 3.12, plus a bunch of syntax warnings for invalid escape sequence:

```
enadataget -h
/Users/cr/micromamba/envs/loculus-ingest/bin/utils.py:106: SyntaxWarning: invalid escape sequence '\.'
  sequence_pattern_1 = re.compile('^[A-Z]{1}[0-9]{5}(\.[0-9]+)?$')
/Users/cr/micromamba/envs/loculus-ingest/bin/utils.py:107: SyntaxWarning: invalid escape sequence '\.'
  sequence_pattern_2 = re.compile('^[A-Z]{2}[0-9]{6}(\.[0-9]+)?$')
/Users/cr/micromamba/envs/loculus-ingest/bin/utils.py:108: SyntaxWarning: invalid escape sequence '\.'
  wgs_sequence_pattern = re.compile('^[A-Z]{4}[0-9]{8,9}(\.[0-9]+)?$')
/Users/cr/micromamba/envs/loculus-ingest/bin/utils.py:109: SyntaxWarning: invalid escape sequence '\.'
  coding_pattern = re.compile('^[A-Z]{3}[0-9]{5}(\.[0-9]+)?$')
/Users/cr/micromamba/envs/loculus-ingest/bin/utils.py:117: SyntaxWarning: invalid escape sequence '\.'
  assembly_pattern = re.compile('^GCA_[0-9]{9}(\.[0-9]+)?$')
Traceback (most recent call last):
  File "/Users/cr/micromamba/envs/loculus-ingest/bin/enaDataGet.py", line 25, in <module>
    import sequenceGet
  File "/Users/cr/micromamba/envs/loculus-ingest/bin/sequenceGet.py", line 26, in <module>
    import utils
  File "/Users/cr/micromamba/envs/loculus-ingest/bin/utils.py", line 32, in <module>
    from configparser import SafeConfigParser
ImportError: cannot import name 'SafeConfigParser' from 'configparser' (/Users/cr/micromamba/envs/loculus-ingest/lib/python3.12/configparser.py). Did you mean: 'RawConfigParser'?
```

**Comment by lilim-ebi** [comment]
Hi, sorry for taking so long, I didn't manage to get around to this for a while. I released a new version now: [enaBrowserTools-v1.7.2](https://github.com/enasequence/enaBrowserTools/releases/tag/v1.7.2)
